services:
  service1:
    build: ./service1
    ports:
      - "8080:8080"
  service2:
    build: ./service2
    environment:
      SERVICE1_URL: http://service1:8080
    depends_on:
      - service1
    ports:
      - "8081:8080" 