[tool.semantic_release]
version_toml = ["pyproject.toml:tool.semantic_release.version"]
version = "2.1.0"
tag_format = "service1-v{version}"
branch = "main"
upload_to_pypi = false
upload_to_release = false
build_command = ""
commit_message = "chore(service1): release {version}"