on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get version id (latest commit SHA)
      id: version
      run: |
        VERSION=$(git rev-parse --short HEAD)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Using version: $VERSION"

    - name: Build both
      run: |
        docker compose up --build -d

    - name: Run python tests
      run: |
        pip install -r requirements.txt
        pytest tests/unit
        pytest tests/integration

    - name: Push to Dockerhub
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker push jetpans/avl-services:service1-${VERSION}

    - name: Cleanup
      if: always()
      run: |
        docker compose down
