on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # Needed to push commits and tags
  pull-requests: write  # Needed for releases
  issues: write  # Needed for releases


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: "Install python dependencies"
      run: |
        pip install -r requirements.txt
      


    - name: Detect changed services
      id: changes
      run: |
        COMMIT_MSG=$(git log -1 --pretty=%B)

        SERVICE1_RELEASE=false
        SERVICE2_RELEASE=false

        if [[ "$COMMIT_MSG" == feat\(service1\)* ]] || [[ "$COMMIT_MSG" == fix\(service1\)* ]]; then
            SERVICE1_RELEASE=true
        fi

        if [[ "$COMMIT_MSG" == feat\(service2\)* ]] || [[ "$COMMIT_MSG" == fix\(service2\)* ]]; then
            SERVICE2_RELEASE=true
        fi

        echo "SERVICE1_RELEASE=$SERVICE1_RELEASE" >> $GITHUB_ENV
        echo "SERVICE2_RELEASE=$SERVICE2_RELEASE" >> $GITHUB_ENV

    - name: Build both
      run: |
        docker compose up --build -d

    - name: Run python tests
      run: |
        pytest tests/unit
        pytest tests/integration


    - name: Push to Dockerhub
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

         if [[ "$SERVICE1_RELEASE" == "true" ]]; then
          cd service1
          VERSION_SERVICE1=$(semantic-release version --print)
          semantic-release version
          docker tag jetpans/avl-services:service1-latest jetpans/avl-services:service1-${VERSION_SERVICE1}
          docker push jetpans/avl-services:service1-${VERSION_SERVICE1}
          cd ..
        fi
        if [[ "$SERVICE2_RELEASE" == "true" ]]; then
          cd service2
          VERSION_SERVICE2=$(semantic-release version --print)
          semantic-release version
          docker tag jetpans/avl-services:service2-latest jetpans/avl-services:service2-${VERSION_SERVICE2}
          docker push jetpans/avl-services:service2-${VERSION_SERVICE2}
          cd ..
        fi


    
    - name: Cleanup
      if : always()
      run: |
        docker compose down
